export const ADMIN_FETCH_USERS_REQUEST = 'ADMIN_FETCH_USERS_REQUEST';
export const ADMIN_FETCH_USERS_SUCCESS = 'ADMIN_FETCH_USERS_SUCCESS';
export const ADMIN_FETCH_USERS_ERROR = 'ADMIN_FETCH_USERS_ERROR';

export const ADMIN_VERIFY_USER_REQUEST = 'ADMIN_VERIFY_USER_REQUEST';
export const ADMIN_VERIFY_USER_SUCCESS = 'ADMIN_VERIFY_USER_SUCCESS';
export const ADMIN_VERIFY_USER_ERROR = 'ADMIN_VERIFY_USER_ERROR';