export const CREATE_DISH_REQUEST = 'CREATE_DISH_REQUEST'
export const CREATE_DISH_SUCCESS = 'CREATE_DISH_SUCCESS'
export const CREATE_DISH_ERROR = 'CREATE_DISH_ERROR'

export const FETCH_DISHES_REQUEST = 'FETCH_DISHES_REQUEST'
export const FETCH_DISHES_SUCCESS = 'FETCH_DISHES_SUCCESS'
export const FETCH_DISHES_ERROR = 'FETCH_DISHES_ERROR'

export const DELETE_DISH_REQUEST = 'DELETE_DISH_REQUEST'
export const DELETE_DISH_SUCCESS = 'DELETE_DISH_SUCCESS'
export const DELETE_DISH_ERROR = 'DELETE_DISH_ERROR'

export const UPDATE_DISH_REQUEST = 'UPDATE_DISH_REQUEST'
export const UPDATE_DISH_SUCCESS = 'UPDATE_DISH_SUCCESS'
export const UPDATE_DISH_ERROR = 'UPDATE_DISH_ERROR'

export const UPLOAD_DISH_IMAGE_REQUEST = 'UPLOAD_DISH_IMAGE_REQUEST'
export const UPLOAD_DISH_IMAGE_SUCCESS = 'UPLOAD_DISH_IMAGE_SUCCESS'
export const UPLOAD_DISH_IMAGE_ERROR = 'UPLOAD_DISH_IMAGE_ERROR'

export const UPDATE_DISH_AVAILABILITY_REQUEST =
  'UPDATE_DISH_AVAILABILITY_REQUEST'
export const UPDATE_DISH_AVAILABILITY_SUCCESS =
  'UPDATE_DISH_AVAILABILITY_SUCCESS'
export const UPDATE_DISH_AVAILABILITY_ERROR = 'UPDATE_DISH_AVAILABILITY_ERROR'

export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';

export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';