export const SET_LANGUAGE = 'SET_LANGUAGE'

export const FETCH_PUBLIC_DISHES_REQUEST = 'FETCH_PUBLIC_DISHES_REQUEST'
export const FETCH_PUBLIC_DISHES_SUCCESS = 'FETCH_PUBLIC_DISHES_SUCCESS'
export const FETCH_PUBLIC_DISHES_ERROR = 'FETCH_PUBLIC_DISHES_ERROR'
